FROM java:8

ENV RABBITMQ_HOSTNAME ${RABBITMQ_HOSTNAME}
ENV RABBITMQ_PORT ${RABBITMQ_PORT}
ENV RABBITMQ_USERNAME ${RABBITMQ_USERNAME}
ENV RABBITMQ_PASSWORD ${RABBITMQ_PASSWORD}

VOLUME /tmp
ADD  build/libs/securityMicroservice-0.0.1-SNAPSHOT.jar entry.jar
ENTRYPOINT ["java","-jar","entry.jar"]
